import dotenv
import os
from gene_enrichment_agent import GeneEnrichmentAgent
from gprofiler import GProfiler
import json
import random
import time
dotenv.load_dotenv()

open_ai_api_key = os.getenv("OPENAI_API_KEY")

gea = GeneEnrichmentAgent(open_ai_api_key, num_papers=20)

with open("testing/background_genes.txt", "r") as f:
    background_genes = f.read().splitlines()

# Astrocytes
genes = [
    "Mt3", "Slc1a2", "Clu", "Aldoc", "Atp1a2", "Sparcl1", "Apoe", "Ckb", "Mt1", "Glul",
    "Slc1a3", "Plpp3", "Gpr37l1", "Cst3", "Ntsr2", "Ptn", "Atp1b2", "Tspan7", "Prnp", "Cpe",
    "Cspg5", "Htra1", "Bcan", "Ptprz1", "Ndrg2", "Cldn10", "Mfge8", "Acsl3", "Gja1", "S1pr1",
    "Malat1", "Ntrk2", "Gstm1", "Scg3", "Slc4a4", "Ttyh1", "Prdx6", "Cd81", "Slc6a1", "F3",
    "Gpm6a", "Luzp2", "Pla2g7", "Lsamp", "Gstm5", "Dbi", "Slc7a10", "Gm3764", "Serpine2", "Chchd10",
    "Mt2", "Ldhb", "Acsbg1", "Cxcl14", "mt-Nd2", "Gpm6b", "Gjb6", "Glud1", "Tsc22d4", "Ntm",
    "Dclk1", "Mlc1", "Phyhipl", "Aqp4", "Fam107a", "Nrxn1", "Mmd2", "Acsl6", "Slc38a3", "Gnao1",
    "Cmtm5", "Qk", "Slc6a11", "Nkain4", "Scd2", "Fxyd1", "Hepacam", "Gria2", "Msmo1", "Tubb2b",
    "mt-Nd4l", "mt-Nd4", "mt-Cytb", "mt-Atp8", "Btbd17", "S100a1", "S100a16", "Slco1c1", "Fjx1",
    "Ramp1", "mt-Nd1", "Ncam1", "Selenop", "Slc39a12", "mt-Co3", "Fgfr3", "Aplp1", "Pantr1", "Son",
    "Ank2"
]

# # Estrogen process
# genes = [
#         "CYP2C9",
#         "PDGFRA",
#         "UGT2B4",
#         "UGT2B15",
#         "SULT1A1",
#         "UGT1A3",
#         "TIPARP",
#         "CYP1A1",
#         "SULT1E1",
#         "CYP3A5",
#         "UGT2B11",
#         "HSD17B8",
#         "CYP3A7",
#         "SGPL1",
#         "PLEKHA1",
#         "UGT2B17",
#         "CYP2C8",
#         "HSD17B4",
#         "HSD17B10",
#         "HSD17B1",
#         "CHST10",
#         "UGT2B7",
#         "CYP1B1",
#         "UGT2B10",
#         "UGT1A1",
#         "CYP3A4",
#         "UGT1A7",
#         "CYP2D6",
#         "CYP1A2",
#         "UGT2B28"
#     ]

# # Adipogenesis
# genes = [
#     "ABCA1",
#     "ABCB8",
#     "ACAA2",
#     "ACADL",
#     "ACADM",
#     "ACADS",
#     "ACLY",
#     "ACO2",
#     "ACOX1",
#     "ADCY6",
#     "ADIG",
#     "ADIPOQ",
#     "ADIPOR2",
#     "AGPAT3",
#     "AIFM1",
#     "AK2",
#     "ALDH2",
#     "ALDOA",
#     "ANGPT1",
#     "ANGPTL4",
#     "APLP2",
#     "APOE",
#     "ARAF",
#     "ARL4A",
#     "ATL2",
#     "ATP1B3",
#     "ATP5PO",
#     "BAZ2A",
#     "BCKDHA",
#     "BCL2L13",
#     "BCL6",
#     "C3",
#     "CAT",
#     "CAVIN1",
#     "CAVIN2",
#     "CCNG2",
#     "CD151",
#     "CD302",
#     "CD36",
#     "CDKN2C",
#     "CHCHD10",
#     "CHUK",
#     "CIDEA",
#     "CMBL",
#     "CMPK1",
#     "COL15A1",
#     "COL4A1",
#     "COQ3",
#     "COQ5",
#     "COQ9",
#     "COX6A1",
#     "COX7B",
#     "COX8A",
#     "CPT2",
#     "CRAT",
#     "CS",
#     "CYC1",
#     "CYP4B1",
#     "DBT",
#     "DDT",
#     "DECR1",
#     "DGAT1",
#     "DHCR7",
#     "DHRS7",
#     "DHRS7B",
#     "DLAT",
#     "DLD",
#     "DNAJB9",
#     "DNAJC15",
#     "DRAM2",
#     "ECH1",
#     "ECHS1",
#     "ELMOD3",
#     "ELOVL6",
#     "ENPP2",
#     "EPHX2",
#     "ESRRA",
#     "ESYT1",
#     "ETFB",
#     "FABP4",
#     "FAH",
#     "FZD4",
#     "G3BP2",
#     "GADD45A",
#     "GBE1",
#     "GHITM",
#     "GPAM",
#     "GPAT4",
#     "GPD2",
#     "GPHN",
#     "GPX3",
#     "GPX4",
#     "GRPEL1",
#     "HADH",
#     "HIBCH",
#     "HSPB8",
#     "IDH1",
#     "IDH3A",
#     "IDH3G",
#     "IFNGR1",
#     "IMMT",
#     "ITGA7",
#     "ITIH5",
#     "ITSN1",
#     "JAGN1",
#     "LAMA4",
#     "LEP",
#     "LIFR",
#     "LIPE",
#     "LPCAT3",
#     "LPL",
#     "LTC4S",
#     "MAP4K3",
#     "MCCC1",
#     "MDH2",
#     "ME1",
#     "MGLL",
#     "MGST3",
#     "MIGA2",
#     "MRAP",
#     "MRPL15",
#     "MTARC2",
#     "MTCH2",
#     "MYLK",
#     "NABP1",
#     "NDUFA5",
#     "NDUFAB1",
#     "NDUFB7",
#     "NDUFS3",
#     "NKIRAS1",
#     "NMT1",
#     "OMD",
#     "ORM1",
#     "PDCD4",
#     "PEMT",
#     "PEX14",
#     "PFKFB3",
#     "PFKL",
#     "PGM1",
#     "PHLDB1",
#     "PHYH",
#     "PIM3",
#     "PLIN2",
#     "POR",
#     "PPARG",
#     "PPM1B",
#     "PPP1R15B",
#     "PRDX3",
#     "PREB",
#     "PTCD3",
#     "PTGER3",
#     "QDPR",
#     "RAB34",
#     "REEP5",
#     "REEP6",
#     "RETN",
#     "RETSAT",
#     "RIOK3",
#     "RMDN3",
#     "RNF11",
#     "RREB1",
#     "RTN3",
#     "SAMM50",
#     "SCARB1",
#     "SCP2",
#     "SDHB",
#     "SDHC",
#     "SLC19A1",
#     "SLC1A5",
#     "SLC25A1",
#     "SLC25A10",
#     "SLC27A1",
#     "SLC5A6",
#     "SLC66A3",
#     "SNCG",
#     "SOD1",
#     "SORBS1",
#     "SOWAHC",
#     "SPARCL1",
#     "SQOR",
#     "SSPN",
#     "STAT5A",
#     "STOM",
#     "SUCLG1",
#     "SULT1A1",
#     "TALDO1",
#     "TANK",
#     "TKT",
#     "TOB1",
#     "TST",
#     "UBC",
#     "UBQLN1",
#     "UCK1",
#     "UCP2",
#     "UQCR10",
#     "UQCR11",
#     "UQCRC1",
#     "UQCRQ",
#     "VEGFB",
#     "YWHAG"
# ]

# # panglao cell
# with open("testing/panglao_cells.gmt", "r") as f:
#     panglao_cells = [line.strip().split("\t") for line in f.readlines()]
#     panglao_cells = [{
#         "name": term[0],
#         "genes": term[1:] 
#     } for term in panglao_cells if len(term[1:]) >= 5]

random_genes = random.sample(background_genes, 500)

search_terms = ["brain", "tumor", "cancer"]
context = "This gene list represents a cell cluster identified in a mouse GBM tumor."
email = "cboyce3@mgh.harvard.edu"

genes = ["AKIRIN2", "PELI1", "TNIP2", "CD81", "TLR9", "SH3KBP1", "IL6", "NOD2", "TICAM1", "TNFSF4"]
genes1 = ["ID2", "SERPINE2", "BMP2", "SHH", "IL6ST", "HES1", "CLCF1", "MAG", "LIF", "NOTCH1", "BIN1"]

print(len(gea.literature.search_literature(random_genes, email, [])))

# themed_results = gea.run_analysis(genes,
#                                   email=email,
#                                   background_genes=background_genes,
#                                   ranked=False,
#                                   search_terms=search_terms,
#                                   context=context,
#                                   analysis_name="Astrocytes")
